### ISSUE TITLE
[Bug]: Crash upon opening nether bridge chests in 1.19 (build brutalbosses-1.19.1-5.5.jar)

### ISSUE THREAD

**Issue by jeffwzhu** [someaddons/dungeonbosses#40]
### Describe the bug you're experiencing

Find a nether fortress, open all the chests.
Around every 1 in 2-3 chests will cause your game to crash with a "java.lang.NoSuchMethodError".

I found the chest in NBTExplorer and it looks like it's a "minecraft:chests/nether_bridge" with a seed of "6459638660099382466".
![nbt](https://user-images.githubusercontent.com/13359007/183351105-fb77f372-3bfc-43a6-8251-5ddc0d9a21a3.png)

Here's a screenshot to help you find the chest.
![2022-08-08_01 10 49](https://user-images.githubusercontent.com/13359007/183351114-6c3a940d-c2df-47ab-824f-1e2c73d819b1.png)

And [here's my game file](https://github.com/someaddons/dungeonbosses/files/9279156/New.World.zip).
You should load in right in front of the problematic chest.

If you disable the mod and load back into the same world, you can open the chest no problem. 
My guess is that there's an incompatible item the mod adds to the loot table that causes the game to crash.
I have not extensively tested other types of chests in the game, so there may be others that have the same issue.

I am running Minecraft 1.19 and Forge 41.1.0 with just the Brutal Boss mod.
![installversion](https://user-images.githubusercontent.com/13359007/183351710-dbfbfe23-b4ae-444e-8f45-4e4baf1419e0.png)

I also cannot get this particular release of the mod to work with 1.19.1 and 1.19.2, either. It crashes when I try to launch the game.
But that's a separate issue.

### Reproducability

Some nether bridge chests are open-able. Other chests will cause your game to crash.

But open enough nether fortress chests and you will eventually find one that makes you crash.

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge 

### Logs and Datapacks

https://gist.github.com/jeffwzhu/9b6623f6c4889360458be601cccb5815

**Comment by someaddons** [comment]
ye it seems to be missing a chat function minecraft had changed in 1.19.1 I think the version isnt fully compatible with 1.19, should work on .1 and .2 though

**Comment by DKLYNTLY** [comment]
when are you going to fix it

**Comment by someaddons** [comment]
I'm not backporting to 1.19.1
